const fs = require('fs');
let html = fs.readFileSync('C:/safetypro_complete_frontend/safetypro_reports.html','utf8');

// Find current filter row and replace it
const oldFilterStart = html.indexOf('<!-- ROW 2: Multi-tenant filters');
const oldFilterEnd = html.indexOf('<div class="main">', oldFilterStart);

if(oldFilterStart < 0) { console.log('ROW 2 marker not found, searching for filter row...'); }

// Find the filter row by looking for rpt-org select
const orgSelect = html.indexOf('id="rpt-org"');
if(orgSelect < 0) { console.log('rpt-org not found'); process.exit(1); }

// Find the parent div of the filter row
const filterRowStart = html.lastIndexOf('<div', orgSelect - 300);
// Find end - goes to just before <div class="main">
const mainDivIdx = html.indexOf('<div class="main"');
console.log('Filter row start:', filterRowStart);
console.log('Main div start:', mainDivIdx);
console.log('Current filter HTML (first 200):', html.substring(filterRowStart, filterRowStart+200));

// New filter bar HTML
const NEW_FILTER_BAR = `  <!-- ROW 2: Multi-tenant filter bar with auto-scroll -->
  <div id="rpt-filter-bar" style="border-top:1px solid var(--border);background:var(--raised);flex-shrink:0;position:relative;padding-right:150px;">
    <div id="fbar-fade-left" style="display:none;position:absolute;left:0;top:0;bottom:0;width:32px;background:linear-gradient(to right,var(--raised),transparent);z-index:10;pointer-events:none;"></div>
    <div id="fbar-fade-right" style="position:absolute;right:145px;top:0;bottom:0;width:32px;background:linear-gradient(to left,var(--raised),transparent);z-index:10;pointer-events:none;"></div>
    <button id="fbar-scroll-left" onclick="fbarScroll(-1)" style="display:none;position:absolute;left:2px;top:50%;transform:translateY(-50%);z-index:20;background:var(--card);border:1px solid var(--border);color:var(--t2);width:22px;height:22px;border-radius:5px;cursor:pointer;font-size:12px;line-height:1;">&#8249;</button>
    <div id="fbar-scroll" style="display:flex;align-items:center;gap:6px;padding:5px 16px;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;-ms-overflow-style:none;flex:1;min-width:0;flex-wrap:nowrap;" onscroll="fbarUpdateScroll()">
      <div style="display:flex;align-items:center;gap:4px;flex-shrink:0;font-size:9px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.5px;white-space:nowrap;"><span style="width:6px;height:6px;background:var(--green);border-radius:50%;display:inline-block;"></span>FILTER</div>
      <div style="width:1px;height:18px;background:var(--border);flex-shrink:0;"></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Company</label><select id="rpt-org" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:150px;"><option value="">All Companies</option><option value="ieccl">IL&amp;FS Engineering (IECCL)</option><option value="abc">Contractor ABC</option><option value="xyz">Contractor XYZ</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Project</label><select id="rpt-project" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:160px;"><option value="">All Projects</option><option value="bbrp">Birpur Bihpur Road (NH131)</option><option value="alpha">Site Alpha — Mumbai Metro</option><option value="tirora">Tirora Power Plant</option><option value="brahmapur">Brahmapur WTP</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Zone / Area</label><select id="rpt-zone" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:130px;"><option value="">All Zones</option><option value="zone-a">Zone A</option><option value="zone-b">Zone B</option><option value="zone-c">Zone C</option><option value="camp">Labour Camp</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Period</label><select id="rpt-period" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:130px;"><option value="mar26">March 2026</option><option value="feb26">February 2026</option><option value="jan26">January 2026</option><option value="q1-26">Q1 2026 (Jan–Mar)</option><option value="q4-25">Q4 2025 (Oct–Dec)</option><option value="fy26">FY 2025–26</option><option value="custom">Custom Range...</option></select></div>
      <div id="rpt-custom-range" style="display:none;flex-shrink:0;gap:4px;align-items:center;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">From</label><input type="date" id="rpt-date-from" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-size:11px;padding:3px 7px;border-radius:5px;outline:none;"><label style="font-size:9px;color:var(--t3);font-weight:600;margin:0 2px;text-transform:uppercase;">To</label><input type="date" id="rpt-date-to" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-size:11px;padding:3px 7px;border-radius:5px;outline:none;"></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Department</label><select id="rpt-dept" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:120px;"><option value="">All Depts</option><option value="hse">HSE</option><option value="engineering">Engineering</option><option value="quality">Quality</option><option value="hr">HR</option><option value="admin">Admin</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Standard</label><select id="rpt-standard" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:130px;"><option value="">All Standards</option><option value="iso45001">ISO 45001:2018</option><option value="iso14001">ISO 14001:2015</option><option value="iso9001">ISO 9001:2015</option><option value="factory">Factories Act 1948</option><option value="bocw">BOCW Act 1996</option><option value="ilo">ILO-OSH 2001</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Workforce</label><select id="rpt-workforce" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:120px;"><option value="">All Types</option><option value="direct">Direct Workers</option><option value="contractor">Contractor</option><option value="subcontractor">Sub-contractor</option><option value="staff">Staff / Officers</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Severity</label><select id="rpt-severity" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:120px;"><option value="">All Severity</option><option value="fatal">Fatality</option><option value="lti">LTI</option><option value="mtc">MTC</option><option value="nearmiss">Near Miss</option><option value="unsafe">Unsafe Act/Condition</option></select></div>
      <div style="flex-shrink:0;"><label style="font-size:9px;color:var(--t3);font-weight:600;display:block;margin-bottom:2px;text-transform:uppercase;">Status</label><select id="rpt-status" onchange="rptApplyFilters()" style="background:var(--card);border:1px solid var(--border);color:var(--t1);font-family:var(--fb);font-size:11px;padding:3px 22px 3px 7px;border-radius:5px;cursor:pointer;outline:none;min-width:110px;"><option value="">All Status</option><option value="open">Open</option><option value="inprogress">In Progress</option><option value="closed">Closed</option><option value="overdue">Overdue</option></select></div>
      <div style="flex-shrink:0;width:8px;"></div>
      <button onclick="rptClearFilters()" id="rpt-clear-btn" style="display:none;flex-shrink:0;background:var(--r-s);border:1px solid var(--r-b);color:var(--red);font-family:var(--fb);font-size:10px;font-weight:600;padding:4px 10px;border-radius:5px;cursor:pointer;white-space:nowrap;">&#x2715; Clear</button>
    </div>
    <button id="fbar-scroll-right" onclick="fbarScroll(1)" style="display:none;position:absolute;right:147px;top:50%;transform:translateY(-50%);z-index:20;background:var(--card);border:1px solid var(--border);color:var(--t2);width:22px;height:22px;border-radius:5px;cursor:pointer;font-size:12px;line-height:1;">&#8250;</button>
    <div id="rpt-export-wrap" style="position:absolute;right:8px;top:50%;transform:translateY(-50%);z-index:20;">
      <button onclick="rptToggleExport()" style="background:var(--green);color:#0B0E12;border:none;font-family:var(--fh);font-size:11px;font-weight:700;padding:5px 12px;border-radius:6px;cursor:pointer;display:flex;align-items:center;gap:5px;white-space:nowrap;"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>Export &#9662;</button>
      <div id="rpt-export-menu" style="display:none;position:absolute;top:calc(100% + 4px);right:0;background:var(--card);border:1px solid var(--border);border-radius:8px;padding:4px;min-width:160px;z-index:999;box-shadow:0 8px 24px rgba(0,0,0,.4);">
        <div onclick="rptExport('pdf')" style="display:flex;align-items:center;gap:8px;padding:7px 10px;border-radius:5px;cursor:pointer;font-size:11px;color:var(--t1);" onmouseover="this.style.background='var(--raised)'" onmouseout="this.style.background='transparent'"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#EF4444" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"/></svg>Export as PDF</div>
        <div onclick="rptExport('excel')" style="display:flex;align-items:center;gap:8px;padding:7px 10px;border-radius:5px;cursor:pointer;font-size:11px;color:var(--t1);" onmouseover="this.style.background='var(--raised)'" onmouseout="this.style.background='transparent'"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#22C55E" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"/></svg>Export as Excel (.xlsx)</div>
        <div onclick="rptExport('word')" style="display:flex;align-items:center;gap:8px;padding:7px 10px;border-radius:5px;cursor:pointer;font-size:11px;color:var(--t1);" onmouseover="this.style.background='var(--raised)'" onmouseout="this.style.background='transparent'"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#3B82F6" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"/></svg>Export as Word (.docx)</div>
        <div style="height:1px;background:var(--border);margin:3px 0;"></div>
        <div onclick="rptExport('print')" style="display:flex;align-items:center;gap:8px;padding:7px 10px;border-radius:5px;cursor:pointer;font-size:11px;color:var(--t2);" onmouseover="this.style.background='var(--raised)'" onmouseout="this.style.background='transparent'"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>Print</div>
      </div>
    </div>
  </div>
  <style>#fbar-scroll::-webkit-scrollbar{display:none}</style>
  <script>
  function fbarScroll(dir){var el=document.getElementById('fbar-scroll');if(el)el.scrollBy({left:dir*200,behavior:'smooth'});setTimeout(fbarUpdateScroll,250);}
  function fbarUpdateScroll(){var el=document.getElementById('fbar-scroll');if(!el)return;var atL=el.scrollLeft<=4,atR=el.scrollLeft>=el.scrollWidth-el.clientWidth-4;var lB=document.getElementById('fbar-scroll-left'),rB=document.getElementById('fbar-scroll-right'),lF=document.getElementById('fbar-fade-left'),rF=document.getElementById('fbar-fade-right');if(lB)lB.style.display=atL?'none':'block';if(rB)rB.style.display=atR?'none':'block';if(lF)lF.style.display=atL?'none':'block';if(rF)rF.style.display=atR?'none':'block';}
  function rptClearFilters(){['rpt-org','rpt-project','rpt-zone','rpt-dept','rpt-standard','rpt-workforce','rpt-severity','rpt-status'].forEach(function(id){var el=document.getElementById(id);if(el)el.value='';});var p=document.getElementById('rpt-period');if(p)p.value='mar26';var cr=document.getElementById('rpt-custom-range');if(cr)cr.style.display='none';var btn=document.getElementById('rpt-clear-btn');if(btn)btn.style.display='none';if(typeof rptApplyFilters==='function')rptApplyFilters();}
  document.addEventListener('change',function(e){if(e.target&&e.target.id==='rpt-period'){var cr=document.getElementById('rpt-custom-range');if(cr)cr.style.display=e.target.value==='custom'?'flex':'none';}});
  window.addEventListener('load',function(){setTimeout(fbarUpdateScroll,500);});
  </script>

`;

// Replace old filter row
const oldStart = filterRowStart;
const oldEnd = mainDivIdx;
html = html.slice(0, oldStart) + NEW_FILTER_BAR + html.slice(oldEnd);
console.log('✓ New filter bar injected');

fs.writeFileSync('C:/safetypro_complete_frontend/safetypro_reports.html', Buffer.from(html,'utf8'));
console.log('Saved. Size:', html.length);
